/**
 * Report export — PDF / Excel / CSV.
 *
 * Strategy (backend-authoritative):
 *   1. Ask the FastAPI backend to render the file:
 *        GET /reports/{id}/export?format=pdf|xlsx|csv   ->  binary body
 *      If it answers, that file is streamed straight to the user.
 *   2. If the backend does not implement that endpoint (404/405/501) or the
 *      app is running without VITE_API_BASE_URL, the file is rendered in the
 *      browser **from the same report record the API returned** — no
 *      placeholder content, no fabricated numbers.
 */
import { ApiError, apiFetchBlob } from "./api-client";
import type { ReportItem } from "./types";

export type ExportFormat = "pdf" | "xlsx" | "csv";

export interface ExportResult {
  filename: string;
  bytes: number;
  source: "backend" | "client";
}

const EXT: Record<ExportFormat, string> = { pdf: "pdf", xlsx: "xlsx", csv: "csv" };

function slug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function filenameFor(report: ReportItem, format: ExportFormat) {
  const stamp = new Date(report.generatedAt).toISOString().slice(0, 10);
  return `sentinelops-${slug(report.name)}-${stamp}.${EXT[format]}`;
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

/** Tabular representation of a report record — shared by all three formats. */
function rowsFor(report: ReportItem): string[][] {
  return report.summary.map((s) => [s.label, s.value]);
}

function metaFor(report: ReportItem): string[][] {
  return [
    ["Report", report.name],
    ["Type", report.type],
    ["Reporting period", report.period],
    ["Status", report.status],
    ["Generated at", new Date(report.generatedAt).toLocaleString()],
    ["Generated by", report.generatedBy],
    ["Exported at", new Date().toLocaleString()],
  ];
}

/* ------------------------------------------------------------ client render */

async function renderPdf(report: ReportItem): Promise<Blob> {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const width = doc.internal.pageSize.getWidth();

  // SentinelOps branding band
  doc.setFillColor(9, 12, 16);
  doc.rect(0, 0, width, 74, "F");
  doc.setFillColor(34, 211, 238);
  doc.rect(0, 74, width, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("SentinelOps", 40, 36);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(160, 174, 192);
  doc.text("Security Operations Center — Reporting", 40, 52);
  doc.text(`Generated ${new Date(report.generatedAt).toLocaleString()}`, width - 40, 52, { align: "right" });

  doc.setTextColor(20, 24, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(report.name, 40, 110);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 100, 115);
  doc.text(`${report.period}  ·  ${report.type}`, 40, 126);

  autoTable(doc, {
    startY: 146,
    head: [["Report metadata", ""]],
    body: metaFor(report),
    theme: "grid",
    headStyles: { fillColor: [17, 24, 33], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 160, fontStyle: "bold" } },
  });

  const rows = rowsFor(report);
  autoTable(doc, {
    startY: (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20,
    head: [["Summary metric", "Value"]],
    body: rows.length ? rows : [["No data available for this reporting period", "—"]],
    theme: "striped",
    headStyles: { fillColor: [34, 211, 238], textColor: 12, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 300 } },
  });

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140, 150, 165);
    doc.text(
      `SentinelOps · ${report.name} · page ${i} of ${pages}`,
      width / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: "center" },
    );
  }
  return doc.output("blob");
}

async function renderXlsx(report: ReportItem): Promise<Blob> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  const metaSheet = XLSX.utils.aoa_to_sheet([["SentinelOps report export"], [], ...metaFor(report)]);
  metaSheet["!cols"] = [{ wch: 24 }, { wch: 52 }];
  XLSX.utils.book_append_sheet(wb, metaSheet, "Overview");

  const rows = rowsFor(report);
  const dataSheet = XLSX.utils.aoa_to_sheet([
    ["Summary metric", "Value"],
    ...(rows.length ? rows : [["No data available for this reporting period", ""]]),
  ]);
  dataSheet["!cols"] = [{ wch: 46 }, { wch: 24 }];
  XLSX.utils.book_append_sheet(wb, dataSheet, "Summary");

  const out = XLSX.write(wb, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
  return new Blob([out], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
}

function csvCell(value: string) {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

function renderCsv(report: ReportItem): Blob {
  const rows = rowsFor(report);
  const lines = [
    ...metaFor(report).map(([k, v]) => `# ${k},${csvCell(v ?? "")}`),
    "",
    "metric,value",
    ...(rows.length
      ? rows.map(([k, v]) => `${csvCell(k ?? "")},${csvCell(v ?? "")}`)
      : ["No data available for this reporting period,"]),
  ];
  return new Blob([`${lines.join("\r\n")}\r\n`], { type: "text/csv;charset=utf-8;" });
}

async function renderLocally(report: ReportItem, format: ExportFormat): Promise<Blob> {
  if (format === "pdf") return renderPdf(report);
  if (format === "xlsx") return renderXlsx(report);
  return renderCsv(report);
}

/* -------------------------------------------------------------- public API */

export async function exportReport(report: ReportItem, format: ExportFormat): Promise<ExportResult> {
  if (report.status !== "ready") {
    throw new Error(`Report "${report.name}" is ${report.status} — it cannot be exported yet.`);
  }

  const filename = filenameFor(report, format);
  let blob: Blob | null = null;
  let source: ExportResult["source"] = "backend";

  try {
    blob = await apiFetchBlob(`/reports/${report.id}/export?format=${format}`);
    if (blob.size === 0) blob = null;
  } catch (error) {
    const status = error instanceof ApiError ? error.status : -1;
    // 503 = no VITE_API_BASE_URL, 404/405/501 = endpoint not implemented yet.
    if (![503, 404, 405, 501, 0].includes(status)) throw error;
    blob = null;
  }

  if (!blob) {
    blob = await renderLocally(report, format);
    source = "client";
  }

  download(blob, filename);
  return { filename, bytes: blob.size, source };
}
